bool   ftpSend(Client&, const String&);
int    ftpReadCode(Client&, String* = nullptr, uint32_t = 8000);
bool   ftpExpect(Client&, int, uint32_t = 8000);
bool   ftpEnterPassive(Client&, uint16_t &dataPort);
bool   ftpListNamesContains(Client&, const String& ctrlHost, const String& dir, const String& fileNameOnly, uint32_t timeoutMs=8000);
bool   ftpFileExists(Client&, const String& remotePath, const String& ctrlHost);
String ftpUniqueName(Client&, const String& name, const String& ctrlHost);
bool   ensureTimeSynced(uint32_t minEpoch=1700000000UL, uint32_t waitMs=15000);
String macNoSep();
String finalDataName();
bool   ftpRename(Client&, const String& from, const String& to);
bool   ftpUploadWithUniqueThenRename(Client&, const String& ctrlHost, const char* localPath, const String& desiredRemoteName, bool (*storUploadFn)(Client&, const String&, const char*));
